name: CI Workflow # The name of the workflow

on: # Defines the events that trigger the workflow
  push: # Trigger the workflow on pushes to specific branches
    branches:
      - main
  pull_request: # Trigger the workflow on pull requests to specific branches
    branches:
      - main

jobs:
  test: # Name of the job
    runs-on: ubuntu-latest # Specifies the operating system to run the job

    steps:
      - name: Checkout code # Step to clone the repository
        uses: actions/checkout@v4 # Official GitHub Action to fetch repository content

      - name: Set up Python # Step to set up Python
        uses: actions/setup-python@v5 # Official GitHub Action to install and configure Python
        with:
          python-version: '>=3.10' # Specifies Python version to use

      - name: Install Poetry # Step to install Poetry
        run: pipx install poetry
        shell: bash

      - name: Install Dependencies # Step to install project dependencies
        run: poetry install

      # Updated steps to use PyInvoke
      - name: Run Tests # Run tests using the invoke task
        run: poetry run invoke test

      - name: Run Linting # Run linting using the invoke task
        run: poetry run invoke lint

      - name: Run Typing Checks # Run typing checks using the invoke task
        run: poetry run invoke type
